# Generated by Django 4.2.2 on 2023-06-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acetelapp', '0002_rename_training_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField(max_length=225)),
                ('question', models.IntegerField()),
            ],
        ),
    ]
