# Generated by Django 4.2.2 on 2023-07-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acetelapp', '0004_exam_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
