# Generated by Django 4.2.2 on 2023-07-02 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acetelapp', '0003_exam'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredcourse',
            name='created_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registeredcourse',
            name='currency',
            field=models.CharField(default='NGN', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registeredcourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acetelapp.course'),
        ),
        migrations.AlterField(
            model_name='registeredcourse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
