# Generated by Django 4.2.2 on 2023-07-03 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_registeredcourse_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredcourse',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
