# Generated by Django 4.2.2 on 2023-07-03 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_payment_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registeredcourse',
            options={'ordering': ('-date_created',)},
        ),
        migrations.RemoveField(
            model_name='registeredcourse',
            name='created_time',
        ),
        migrations.AddField(
            model_name='registeredcourse',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='registeredcourse',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registeredcourse',
            name='ref',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='registeredcourse',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registeredcourse',
            name='amount',
            field=models.PositiveBigIntegerField(),
        ),
    ]
