# Generated by Django 4.2.2 on 2023-07-03 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acetelapp', '0003_exam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0011_alter_registeredcourse_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acetelapp.course'),
        ),
        migrations.AlterField(
            model_name='registeredcourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
