# Generated by Django 4.2.2 on 2023-07-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_alter_registeredcourse_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredcourse',
            old_name='ref',
            new_name='paystack_ref',
        ),
    ]
