# Generated by Django 4.2.2 on 2023-07-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0018_registeredexam_currency_registeredexam_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredexam',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
