# Generated by Django 4.2.2 on 2023-06-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MA', 'male'), ('FE', 'female')], default='MA', max_length=10),
        ),
    ]
