# Generated by Django 4.2.2 on 2023-06-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MA', 'male'), ('FE', 'female'), ('SE', 'Select gender')], default='SE', max_length=10),
        ),
    ]
